<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="24.393" tests="1" failures="1">
  <testsuite name="Root Suite" timestamp="2023-12-13T22:05:59" tests="0" file="cypress/integration/second.spec.js" time="0.000" failures="0">
  </testsuite>
  <testsuite name="logout" timestamp="2023-12-13T22:05:59" tests="1" time="24.371" failures="1">
    <testcase name="logout Verify it logout successfully" time="7.580" classname="Verify it logout successfully">
      <failure message="Timed out retrying after 4000ms: expected &apos;&lt;ul.nav.navbar-nav.pull-xs-right&gt;&apos; to contain &apos;Sign up1&apos;" type="AssertionError"><![CDATA[AssertionError: Timed out retrying after 4000ms: expected '<ul.nav.navbar-nav.pull-xs-right>' to contain 'Sign up1'
    at Context.eval (http://localhost:4200/__cypress/tests?p=cypress\integration\second.spec.js:106:27)]]></failure>
    </testcase>
  </testsuite>
</testsuites>