<?xml version="1.0"?>
<testsuites>
<testsuite name="Root Suite" timestamp="2023-12-13T22:05:22" tests="0" file="cypress/integration/firstTest.spec.js" time="0.000" failures="0"></testsuite>
<testsuite name="Login the new project" timestamp="2023-12-13T22:05:22" tests="4" time="33.641" failures="0">
  
  <testcase name="Login the new project Verify correct response and request" time="9.872" classname="Verify correct response and request"></testcase>
  
  <testcase name="Login the new project taglist" time="2.926" classname="taglist"></testcase>
  
  <testcase name="Login the new project verify global " time="6.435" classname="verify global "></testcase>
  
  <testcase name="Login the new project Delete the article from API" time="14.244" classname="Delete the article from API"></testcase>
  
</testsuite>

<testsuite name="Root Suite" timestamp="2023-12-13T22:05:59" tests="0" file="cypress/integration/second.spec.js" time="0.000" failures="0"></testsuite>
<testsuite name="logout" timestamp="2023-12-13T22:05:59" tests="1" time="24.371" failures="1">
  
  <testcase name="logout Verify it logout successfully" time="7.580" classname="Verify it logout successfully">
    
    <failure message="Timed out retrying after 4000ms: expected &apos;&lt;ul.nav.navbar-nav.pull-xs-right&gt;&apos; to contain &apos;Sign up1&apos;" type="AssertionError"><![CDATA[AssertionError: Timed out retrying after 4000ms: expected '<ul.nav.navbar-nav.pull-xs-right>' to contain 'Sign up1'
    at Context.eval (http://localhost:4200/__cypress/tests?p=cypress\integration\second.spec.js:106:27)]]></failure>
    
  </testcase>
  
</testsuite>

<testsuite name="Root Suite" timestamp="2023-12-13T22:05:22" tests="0" file="cypress/integration/firstTest.spec.js" time="0.000" failures="0"/>
<testsuite name="Login the new project" timestamp="2023-12-13T22:05:22" tests="4" time="33.641" failures="0">
  
  <testcase name="Login the new project Verify correct response and request" time="9.872" classname="Verify correct response and request"/>
  
  <testcase name="Login the new project taglist" time="2.926" classname="taglist"/>
  
  <testcase name="Login the new project verify global " time="6.435" classname="verify global "/>
  
  <testcase name="Login the new project Delete the article from API" time="14.244" classname="Delete the article from API"/>
  
</testsuite>
<testsuite name="Root Suite" timestamp="2023-12-13T22:05:59" tests="0" file="cypress/integration/second.spec.js" time="0.000" failures="0"/>
<testsuite name="logout" timestamp="2023-12-13T22:05:59" tests="1" time="24.371" failures="1">
  
  <testcase name="logout Verify it logout successfully" time="7.580" classname="Verify it logout successfully">
    
    <failure message="Timed out retrying after 4000ms: expected &apos;&lt;ul.nav.navbar-nav.pull-xs-right&gt;&apos; to contain &apos;Sign up1&apos;" type="AssertionError"><![CDATA[AssertionError: Timed out retrying after 4000ms: expected '<ul.nav.navbar-nav.pull-xs-right>' to contain 'Sign up1'
    at Context.eval (http://localhost:4200/__cypress/tests?p=cypress\integration\second.spec.js:106:27)]]></failure>
    
  </testcase>
  
</testsuite>
<testsuite name="Root Suite" timestamp="2023-12-13T22:05:22" tests="0" file="cypress/integration/firstTest.spec.js" time="0.000" failures="0"/>
<testsuite name="Login the new project" timestamp="2023-12-13T22:05:22" tests="4" time="33.641" failures="0">
  
  <testcase name="Login the new project Verify correct response and request" time="9.872" classname="Verify correct response and request"/>
  
  <testcase name="Login the new project taglist" time="2.926" classname="taglist"/>
  
  <testcase name="Login the new project verify global " time="6.435" classname="verify global "/>
  
  <testcase name="Login the new project Delete the article from API" time="14.244" classname="Delete the article from API"/>
  
</testsuite>
<testsuite name="Root Suite" timestamp="2023-12-13T22:05:59" tests="0" file="cypress/integration/second.spec.js" time="0.000" failures="0"/>
<testsuite name="logout" timestamp="2023-12-13T22:05:59" tests="1" time="24.371" failures="1">
  
  <testcase name="logout Verify it logout successfully" time="7.580" classname="Verify it logout successfully">
    
    <failure message="Timed out retrying after 4000ms: expected &apos;&lt;ul.nav.navbar-nav.pull-xs-right&gt;&apos; to contain &apos;Sign up1&apos;" type="AssertionError"><![CDATA[AssertionError: Timed out retrying after 4000ms: expected '<ul.nav.navbar-nav.pull-xs-right>' to contain 'Sign up1'
    at Context.eval (http://localhost:4200/__cypress/tests?p=cypress\integration\second.spec.js:106:27)]]></failure>
    
  </testcase>
  
</testsuite>
<testsuite name="Root Suite" timestamp="2023-12-13T22:05:22" tests="0" file="cypress/integration/firstTest.spec.js" time="0.000" failures="0"/>
<testsuite name="Login the new project" timestamp="2023-12-13T22:05:22" tests="4" time="33.641" failures="0">
  
  <testcase name="Login the new project Verify correct response and request" time="9.872" classname="Verify correct response and request"/>
  
  <testcase name="Login the new project taglist" time="2.926" classname="taglist"/>
  
  <testcase name="Login the new project verify global " time="6.435" classname="verify global "/>
  
  <testcase name="Login the new project Delete the article from API" time="14.244" classname="Delete the article from API"/>
  
</testsuite>
<testsuite name="Root Suite" timestamp="2023-12-13T22:05:59" tests="0" file="cypress/integration/second.spec.js" time="0.000" failures="0"/>
<testsuite name="logout" timestamp="2023-12-13T22:05:59" tests="1" time="24.371" failures="1">
  
  <testcase name="logout Verify it logout successfully" time="7.580" classname="Verify it logout successfully">
    
    <failure message="Timed out retrying after 4000ms: expected &apos;&lt;ul.nav.navbar-nav.pull-xs-right&gt;&apos; to contain &apos;Sign up1&apos;" type="AssertionError"><![CDATA[AssertionError: Timed out retrying after 4000ms: expected '<ul.nav.navbar-nav.pull-xs-right>' to contain 'Sign up1'
    at Context.eval (http://localhost:4200/__cypress/tests?p=cypress\integration\second.spec.js:106:27)]]></failure>
    
  </testcase>
  
</testsuite>

</testsuites>